# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-25 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20170725_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='updated_at',
        ),
    ]
